#!/bin/sh

transmit() {
	kill -s "$1" "$pid_ant"
}

tmp="$(mktemp "/tmp/ant-color.XXXXXX")"
rm "$tmp"
mkfifo "$tmp"

exec 3<&0 # save stdin, to pass it to ant
exec 0<&- # close stdin for this script
ant "$@" 0<&3 >"$tmp" 2>&1 &
pid_ant="$!"

ant-colorfilter <"$tmp" &
pid_filter="$!"

saved_trap="$(trap)"
trap "transmit HUP" HUP
trap "transmit INT" INT
trap "transmit TERM" TERM
trap "transmit QUIT" QUIT

wait "$pid_filter"
wait "$pid_ant"
rtn="$?" # return status from ant

rm "$tmp"

eval "$saved_trap"

exit "$rtn"
